name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build .Car by Image Assets
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      

      - name: Web Hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
